# Generated by Django 2.2.11 on 2020-04-11 01:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200411_0102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hbblockdata',
            name='createDate',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 11, 1, 3, 54, 59124, tzinfo=utc), verbose_name='date published'),
        ),
    ]
