# Generated by Django 2.2.11 on 2020-04-11 01:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200411_0103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hbblockdata',
            name='createDate',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published'),
        ),
    ]
