# Generated by Django 2.2.11 on 2020-05-14 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200411_0104'),
    ]

    operations = [
        migrations.AddField(
            model_name='hbblockdata',
            name='email',
            field=models.EmailField(default='unknown', max_length=70),
        ),
    ]
