# Generated by Django 2.2.11 on 2020-05-18 20:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_hbblockdata_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ethAddress', models.CharField(max_length=42)),
                ('email', models.EmailField(default='unknown', max_length=70)),
                ('createDate', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Client Created')),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ethAddress', models.CharField(max_length=42)),
                ('email', models.EmailField(default='unknown', max_length=70)),
                ('repute', models.IntegerField(default=0)),
                ('status', models.IntegerField(default=0)),
                ('has_repute', models.BooleanField(default=False)),
                ('createDate', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Doctor Created')),
            ],
        ),
        migrations.CreateModel(
            name='Mediator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mid', models.IntegerField()),
                ('ethAddress', models.CharField(max_length=42)),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Opinion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oid', models.IntegerField()),
                ('receptionId', models.CharField(max_length=42)),
                ('opinions', models.TextField()),
                ('opinionDate', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Opinion Date')),
            ],
        ),
        migrations.CreateModel(
            name='Reception',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rid', models.CharField(max_length=42)),
                ('mediatorId', models.IntegerField()),
                ('receptionistId', models.CharField(max_length=42)),
                ('adopterId', models.CharField(max_length=42)),
                ('comments', models.TextField()),
                ('opinions', models.TextField()),
                ('status', models.IntegerField(default=0)),
                ('url', models.URLField(max_length=1024)),
                ('hash', models.CharField(max_length=256)),
                ('createDate', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Reception Create Date')),
                ('opinionDate', models.DateTimeField(default=None, verbose_name='Opinion Date')),
                ('confirmDate', models.DateTimeField(default=None, verbose_name='Confirm Date')),
            ],
        ),
        migrations.CreateModel(
            name='Reputation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctorId', models.CharField(max_length=42)),
                ('email', models.CharField(max_length=255)),
                ('repute', models.IntegerField()),
                ('createDate', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Reputation Created')),
                ('updateDate', models.DateTimeField(default=None, verbose_name='Reputation Updated')),
            ],
        ),
        migrations.CreateModel(
            name='SmartContract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contractAddress', models.CharField(max_length=42)),
                ('contractDate', models.DateTimeField(default=django.utils.timezone.now, verbose_name='SmartContract Created')),
                ('contractName', models.CharField(max_length=256)),
                ('contractType', models.IntegerField(default=0)),
            ],
        ),
    ]
