# Generated by Django 2.2.11 on 2020-05-20 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_client_doctor_mediator_opinion_reception_reputation_smartcontract'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reputation',
            options={'ordering': ['updateDate']},
        ),
    ]
