# Generated by Django 2.2.11 on 2020-05-20 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20200520_0045'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reputation',
        ),
        migrations.AlterModelOptions(
            name='reception',
            options={'ordering': ['createDate']},
        ),
    ]
