# Generated by Django 2.2.11 on 2020-05-29 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_deployedcontract'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployedcontract',
            name='repute',
            field=models.IntegerField(default=0),
        ),
    ]
